name: 'Versions'
description: 'Deduce the version to stage and the next SNAPSHOT version'
inputs:
  release-type:
    description: 'The type of release being performed'
outputs:
  stage-version:
    description: 'The version should be staged'
    value: 'foo'
  next-version:
    description: 'The version to use for the next SNAPSHOT'
    value: 'bar'
runs:
  using: composite
  steps:
    - name: Install Utilities
      shell: bash
      run: |
        sudo apt-get -y install libxml2-utils
    - name: Dunno
      shell: bash
      env:
        RELEASE_TYPE: "${{ inputs.release-type }}"
      run: |
        echo "${RELEASE_TYPE}"
        pwd
        ls -l
    - name: More
      shell: bash
      run: ${{ github.action_path }}/versions.sh