name: 'Versions'
description: 'Deduce the version to stage and the next SNAPSHOT version'
inputs:
  current-version:
    description: 'The current version number'
  release-type:
    description: 'The type of release being performed'
outputs:
  stage-version:
    description: 'The version should be staged'
    value: 'foo'
  next-version:
    description: 'The version to use for the next SNAPSHOT'
    value: 'bar'
runs:
  using: composite
  steps:
    - name: Install Utilities
      shell: bash
      run: |
        sudo apt-get -y install libxml2-utils
    - name: Deduce Versions
      shell: bash
      run: ${{ github.action_path }}/deduce-versions.sh
      env:
        CURRENT_VERSION: "${{ inputs.current-version }}"
        RELEASE_TYPE: "${{ inputs.release-type }}"
