name: Build and Deploy Snapshot
on: workflow_dispatch
inputs:
  environment:
    description: 'Environment to run tests against'
    type: environment
    required: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build-and-deploy-snapshot:
    name: Build and Deploy Snapshot
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'spring-io/spring-javaformat' }}
    steps:
      - name: Check Out Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Build and Publish
        uses: ./.github/actions/build
        with:
          publish: true
      - name: Deploy
        uses: spring-io/artifactory-deploy-action@26bbe925a75f4f863e1e529e85be2d0093cac116 # v0.0.1
        with:
          folder: 'distribution-repository'
          uri: 'https://repo.spring.io'
          repository: 'libs-snapshot-local'
          build-name: spring-javaformat
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          signing-key: ${{ secrets.GPG_PRIVATE_KEY }}
          signing-passphrase: ${{ secrets.GPG_PASSPHRASE }}
