name: Build Pull Request
on: pull_request
permissions:
  contents: read
jobs:
  build:
    name: Build Pull Request
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'spring-projects/spring-boot' }}
    steps:
    - name: Set Up and Checkout
      uses: ./.github/actions/setup-and-checkout
    - name: Build
      run: ./mvnw clean install --batch-mode --no-transfer-progress --update-snapshots
