name: Promote
run-name: Promote of '${{ github.ref_name }}' branch by ${{ github.actor }} to '${{ inputs.environment }}' environment
on: 
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: environment
        required: true        
jobs:
  dunno:
    environment: ${{ inputs.environment }}
    name: "Dunno (${{ inputs.environment }})"
    runs-on: ubuntu-latest
    steps:
    - name: Duuno
      run: echo "Dunno"
  more:
    name: "More stuff"
    runs-on: ubuntu-latest
    steps:
    - name: Duuno
      run: echo "Dunno"
