name: Release
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Release Environment'
        type: environment
        required: true
jobs:
  stage:
    name: "Stage (${{ inputs.environment }})"
    runs-on: ubuntu-latest
    steps:
    - name: Check Out
      uses: actions/checkout@v4
    - name: Set Up
      uses: ./.github/actions/setup
    - name: Get Current Version
      id: get-version
      run: echo "current-version=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml)" >> $GITHUB_OUTPUT
    - name: Deduce Versions
      id: deduce-versions
      uses: ./.github/actions/deduce-versions
      with:
        current-version: ${{ steps.get-version.outputs.current-version }}
        release-type: ${{ inputs.environment }}
    - name: Stage Code
      uses: ./.github/actions/stage-code
      if: 'false'
      with:
        current-version: ${{ steps.get-version.outputs.current-version }}
        release-version: ${{ steps.deduce-versions.outputs.release-version }}
        next-version: ${{ steps.deduce-versions.outputs.next-version }}
    - name: Deploy to Staging
      run: echo "Deploy to Staging Here"
    - name: Push
      run: echo "Push Here"
    outputs:
      release-version: ${{ steps.deduce-versions.outputs.release-version }}
  promote:
    name: "Promote (${{ inputs.environment }})"
    needs: stage
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Promote
      run: echo "Promote Here ${RELEASE_VERSION}"
      env:
        RELEASE_VERSION: ${{needs.stage.outputs.release-version}}
