name: Release
run-name: 'Release of "${{ github.ref_name }}" branch by ${{ github.actor }} to "${{ inputs.environment }}" environment'
on: 
    workflow_dispatch:
      inputs:
        environment:
          description: 'Release Environment'
          type: environment
          required: true
jobs:
  stage:
    name: 'Stage to "${{ inputs.environment }}" environment'
    runs-on: ubuntu-latest
    steps:
    - name: Duuno
      run: echo "Dunno"
