name: Release
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Release Environment'
        type: environment
        required: true
jobs:
  stage:
    name: Stage Release
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Code
      uses: actions/checkout@v4
    - name: Debug
      run: |
        echo "Env: ${{ github.event.inputs.environment }}" 
        echo "Env: ${{ github.event.inputs.environment.name }}"         
