name: Release
run-name: "Release of '${{ github.ref_name }}' branch to '${{ inputs.environment }}' environment by ${{ github.actor }}"
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Release Environment'
        type: environment
        required: true
jobs:
  stage:
    name: "Stage to '${{ inputs.environment }}' environment"
    runs-on: ubuntu-latest
    steps:
    - name: Staging
      run: echo "Staging"
  promote:
    name: "Promote to '${{ inputs.environment }}' environment"
    needs: stage
    uses: ./.github/workflows/promote.yml
    with:
      environment: ${{ inputs.environment }}
