name: Release
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Release Environment'
        type: environment
        required: true
jobs:
  stage:
    name: Stage Release
    runs-on: ubuntu-latest
    steps:
    - name: Install Utilities
      run: |
        sudo apt-get -y install libxml2-utils
    - name: Check Out Code
      uses: actions/checkout@v4
