name: Stage
run-name: Stage of ${{ github.ref_name }} by ${{ github.actor }} to '${{ inputs.environment }}' environment
on: 
    workflow_call:
      inputs:
        environment:
          description: 'Release Environment'
          type: environment
          required: true
jobs:
  dunno:
    name: "Dunno (${{ inputs.environment }})"
    runs-on: ubuntu-latest
    steps:
    - name: Duuno
      run: echo "Dunno"
